# Site configuration
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - garth-jekyll-theme.gemspec

# Plugins
plugins:
  - jekyll-paginate

# Jekyll settings
sass:
  style: compressed
permalink: pretty
timezone: Asia/Kolkata

# Jekyll collections settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Site settings
encoding: utf-8
title: "Atharva Attarde"
logo: "/assets/logo.svg"
description: "PhD Student at IISc Bangalore | BioMedIA Lab, CDS"
url: "https://Atharva-Attarde.github.io"
baseurl: ""
lang: en-US
